### ISSUE TITLE
create-react-app is dead

### ISSUE THREAD

**Issue by KaSaNaa** [Isuru2701/YoloUI#1]
React developer team recently removed create-react-app from the official documentation. This means it is no longer the default method of setting up a new project in React. According to [this](https://github.com/reactjs/react.dev/pull/5487) pull request on Github, create-react-app is finally gone.

[Read more](https://dev.to/ag2byte/create-react-app-is-officially-dead-h7o)

**Comment by Isuru2701** [comment]
Huh
